[tool.poetry]
name = "luban_common"
version = "3.0.21"
description = "鲁班API基础库"
authors = ["mongnet <250021520@qq.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/mongnet/luban_common"
repository = "https://github.com/mongnet/luban_common"
keywords = ["HTTP", "api", "test", "requests", "pytest"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.1"
allure-pytest = "^2.11.1"
jsonpath = "^0.82"
pyyaml = "^6.0"
faker = "^14.2.1"
cleo = "^0.8.1"
chevron = "^0.14.0"
py = "^1.11.0"
pytest-html = "3.1.1"
xlrd = "^2.0.1"
pathlib2 = "^2.3.7"
xmltodict = "^0.13.0"
suds-py3 = "^1.4.5"
pytest-rerunfailures = "^10.2"
pytest = "^7.2.0"
"ruamel.yaml" = "^0.17.21"

[tool.poetry.dev-dependencies]
pytest = "^7.2"

[tool.poetry.scripts]
luban = "luban_common.console:main"

[[tool.poetry.source]]
name = "aliyun"
url = "http://mirrors.aliyun.com/pypi/simple/"
default = true

[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"

