base_url : https://autotest.sg.luban.fit/service
weixin_robot: ""
manager :
  username : luban
  password : 111111
  deviceType : WEB
  scope : luban
front :
  realname : 冒烟测试用户
  username : zhangsan10028
  password : RhYi1aA.