setting :
  status : NOW
  baseUrl : https://lubantest.sg.luban.cn
  robot : "ae0fdeb8-8b10-4388-8abb-d8ae21ab8d42"
  scope :
    - 职务管理-编辑职务_测试脚本文件夹_1725431825
  login :
    - path : /service/auth/login
      Location : resp.data.token
      header : access-token
      scope : ~
    - path : /service/auth/luban/login
      Location : resp.data.token
      header : access-token
      scope : ~
    - path : /service/ent-admin-basic-data/token/process
      Location : resp.data
      header : access-token
      scope :
        - /service/process
  filterMethod :
    - options
  filterFile :
    - .js
    - .png
    - .jpg
    - .ico
    - .html
    - .htm
    - .woff2
    - .io
    - .css
    - .map
    - .svg
  filterUrl :
    - /service/auth/login
    - /service/auth/luban/login
  replaceDict :
    null : ~
    true : True
    false : False
  allowRecording :
    - lbuilder.cn
    - luban.cn
    - 47.103.139.42
    - 192.168.13.178
  headers :
    access-token: bwP4153sI1BT1kDSB3q66GrjHnhl03FgtDpKVJjcD9chzMV6oKmEleTM8LHgG6kX