# 替换脚本文件内容，会用到 body 请求体中，比如有些排序参数，没有指定参数时需要有默认处理方式，用替换方式简单、快速、直接
# 只支持key: value 的形式
# 注意冒号后要有空格，这是yaml的语法
# 如果要引用变量或代码，可通过 $变量$ 的方式
currentPage: 1 # 当前页
page: 1 # 也是当前页，设计未统一导致的问题
pageNum: 1 # 也是当前页，设计未统一导致的问题
pageIndex: 1 # 也是当前页，设计未统一导致的问题
page_index: 1 # 也是当前页，设计未统一导致的问题
pageSize: 50 # 分页大小
page_size: 50 # 分页大小
size: 10 # 分页大小
remarks: 自动化测试备注 # 备注
direction: 0 # 排序方式 0 ASC  1 DESC
dictOrder: False # 是否要按字典序排序
status: 0 # 状态默认为0
deptType: 0 # 项目类型(0 默认、1 高速公路、2 一级公路 3 二级公路 4 三级公路 5 四级公路 6 市政公路)
nodeType: 1 # 1标段，2单项，3单位工程
classification: 0 # 类别 0 施工 1监理 2 检测
isAll: True # 是否全部授权
approvalType: 0 # 审批类型: 0-我的待办, 1-我的待发, 2-我的已办