Setting :
  Status : DEBUG
  Url : https://lubantest.sg.luban.cn
  User : testapi
  PSW : 111111
  weixin_robot : "ae0fdeb8-8b10-4388-8abb-d8ae21ab8d42"
  Scope :
    - 职务管理-编辑职务_测试脚本文件夹_1721122070
  login :
    url : /auth-server/auth/token
    rule : resp.data
  filterMethod :
    - options
  filterFile :
    - .js
    - .png
    - .jpg
    - .ico
    - .html
    - .htm
    - .woff2
    - .io
    - .css
    - .map
  filterUrl :
    - service/auth/login
    - https://lubantest.sg.luban.cn/?refreshToken
    - service/ent-admin-user/biz/user
  replaceDict :
    null : ~
    true : True
    false : False
  allowRecording :
    - lbuilder.cn
    - luban.cn
  headers :
    access-token: IGCsSQVp9oi8YS8z3Bk38QbDSxx9A1VA1YATMLS1NAmbVisKpQXA5MMCPZ3AkgKP