setting :
  status : NOW
  baseUrl : https://lubantest.sg.luban.cn
  weixin_robot : "ae0fdeb8-8b10-4388-8abb-d8ae21ab8d42"
  scope :
    - 龙门吊-设备管理_测试脚本文件夹_1670811570
  login :
    - url : service/auth/login
      rule : resp.data.token
      header : access-token
  filterMethod :
    - options
  filterFile :
    - .js
    - .png
    - .jpg
    - .ico
    - .html
    - .htm
    - .woff2
    - .io
    - .css
    - .map
  filterUrl :
    - service/auth/login
    - service/ent-admin-user/biz/user
  replaceDict :
    null : ~
    true : True
    false : False
  allowRecording :
    - lbuilder.cn
    - luban.cn
    - 47.103.139.42
  headers :
    access-token: Ssm16c1gMKfOmozHmFv12nqdCyKUdTfNWbPcQ7T5x0DFV5kw8B6eBElHbM0nkh8K