setting :
  status : NOdW
  baseUrl : https://lubantest.sg.luban.cn
  weixin_robot : "ae0fdeb8-8b10-4388-8abb-d8ae21ab8d42"
  scope :
    - 龙门吊-设备管理_测试脚本文件夹_1670811570
  login :
    url : /auth-server/auth/token
    rule : resp.data
    header : access-token
  filterMethod :
    - options
  filterFile :
    - .js
    - .png
    - .jpg
    - .ico
    - .html
    - .htm
    - .woff2
    - .io
    - .css
    - .map
  filterUrl :
    - service/auth/login
    - service/ent-admin-user/biz/user
  replaceDict :
    null : ~
    true : True
    false : False
  allowRecording :
    - lbuilder.cn
    - luban.cn
  headers :
    access-token: DKXbBEKi6yDQSKH9D7XxTL1Lvn74DT6TnbEHTXBMr6Go0lm3nKOSroWpi4xvv3DV