pds : http://app.lbuilder.cn
ac : http://ac.myluban.com
base_url : http://service.lbuilder.cn
iworks_web: http://lbuilder.cn
iworks_web_old: http://iworks.lbuilder.cn
center_web: http://center.lbuilder.cn
weixin_robot: ""
center:
  username: lb91247
  password: 264f0c676e143da03019f1698304c468
iworksApp :
  username : test
  password : 96e79218965eb72c92a549dd5a325612
  clientVersion: 2.1.0