base_url : http://192.168.13.172/service
weixin_robot: ""
manager :
  username : admin
  password : autotest
  deviceType : WEB
  scope : autotest
normal :
  realname : 冒烟测试用户
  username : test
  password : test
  deviceType : WEB
  scope : autotest