base_url : https://autotest.sg.luban.cn/service
weixin_robot: ""
manager :
  username : admin
  password : autotest
  deviceType : WEB
normal :
  realname : 冒烟测试用户
  username : test
  password : test
  deviceType : WEB